CREATE TABLE IF NOT EXISTS user (
  User_ID VARCHAR(50) PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(120) NOT NULL,
  Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS admin (
  Admin_id VARCHAR(50) PRIMARY KEY,
  Type VARCHAR(100) NOT NULL,
  Email VARCHAR(120) NOT NULL,
  Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  author VARCHAR(120) NOT NULL
);
